In [1]:

# Import required libraries
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
insurance = pd.read_csv("https://raw.githubusercontent.com/stedy/Machine-Learning-with-R-datasets/master/insurance.csv")
insurance.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
# One-Hot Encoding
df = pd.get_dummies(insurance)
df.head()

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,16884.92400,True,False,False,True,False,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False,False,False,True,False
2,28,33.000,3,4449.46200,False,True,True,False,False,False,True,False
3,33,22.705,0,21984.47061,False,True,True,False,False,True,False,False
4,32,28.880,0,3866.85520,False,True,True,False,False,True,False,False

In [6]:
X = df.drop(['charges'], axis=1)
y = df['charges']

In [8]:
X

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27.900,0,True,False,False,True,False,False,False,True
1,18,33.770,1,False,True,True,False,False,False,True,False
2,28,33.000,3,False,True,True,False,False,False,True,False
3,33,22.705,0,False,True,True,False,False,True,False,False
4,32,28.880,0,False,True,True,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...
1333,50,30.970,3,False,True,True,False,False,True,False,False
1334,18,31.920,0,True,False,True,False,True,False,False,False
1335,18,36.850,0,True,False,True,False,False,False,True,False
1336,21,25.800,0,True,False,True,False,False,False,False,True
1337,61,29.070,0,True,False,False,True,False,True,False,False

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
560,46,19.95,2,True,False,True,False,False,True,False,False
1285,47,24.32,0,True,False,True,False,True,False,False,False
1142,52,24.86,0,True,False,True,False,False,False,True,False
969,39,34.32,5,True,False,True,False,False,False,True,False
486,54,21.47,3,True,False,True,False,False,True,False,False

In [11]:
y_train.head()

1291    34828.65400
628     11365.95200
489     10461.97940
850     37270.15120
122      2257.47525
Name: charges, dtype: float64

In [22]:
print(f"Number of rows in test data:", X_test.shape[0])
print(f"Number of rows in train data:", X_train.shape[0])

Number of rows in test data: 268
Number of rows in train data: 1070

In [24]:
tf.random.set_seed(42)

# Create the model
insurance_model = tf.keras.Sequential([
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dense(1),
])

# 2 Compile the Model
insurance_model.compile(loss=tf.keras.losses.mae,
optimizer=tf.keras.optimizers.SGD(),
metrics=["mae"])

insurance_model.fit(X_train, y_train, epochs=100)

Epoch 1/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 10048.0020 - mae: 10048.0020
Epoch 2/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7716.6777 - mae: 7716.6777
Epoch 3/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7507.3169 - mae: 7507.3169
Epoch 4/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7320.2373 - mae: 7320.2373
Epoch 5/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7308.4287 - mae: 7308.4287
Epoch 6/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7642.0132 - mae: 7642.0132
Epoch 7/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7728.1670 - mae: 7728.1670
Epoch 8/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7488.6572 - mae: 7488.6572
Epoch 9/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 7949.6182 - mae: 7949.6182
Epoch 10/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7618.9463 - mae: 7618.9463
Epoch 11/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7505.6162 - mae: 7505.6162
Epoch 12/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7161.3472 - mae: 7161.3472
Epoch 13/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7913.8354 - mae: 7913.8354
Epoch 14/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7640.6245 - mae: 7640.6245
Epoch 15/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7433.2275 - mae: 7433.2275
Epoch 16/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7460.6587 - mae: 7460.6587
Epoch 17/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7508.2700 - mae: 7508.2700
Epoch 18/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7359.0000 - mae: 7359.0000
Epoch 19/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7493.2339 - mae: 7493.2339
Epoch 20/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7570.5381 - mae: 7570.5381
Epoch 21/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7401.7412 - mae: 7401.7412
Epoch 22/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7444.6362 - mae: 7444.6362
Epoch 23/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7568.6938 - mae: 7568.6938
Epoch 24/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7351.0381 - mae: 7351.0381
Epoch 25/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7553.1895 - mae: 7553.1895
Epoch 26/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7463.4214 - mae: 7463.4214
Epoch 27/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7514.9673 - mae: 7514.9673
Epoch 28/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7429.1411 - mae: 7429.1411
Epoch 29/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7604.0371 - mae: 7604.0371
Epoch 30/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7509.9839 - mae: 7509.9839
Epoch 31/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7548.3623 - mae: 7548.3623
Epoch 32/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 7466.6865 - mae: 7466.6865
Epoch 33/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7440.5547 - mae: 7440.5547
Epoch 34/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7400.9126 - mae: 7400.9126
Epoch 35/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7365.5078 - mae: 7365.5078
Epoch 36/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7406.2188 - mae: 7406.2188
Epoch 37/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7463.2280 - mae: 7463.2280
Epoch 38/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7462.4858 - mae: 7462.4858
Epoch 39/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7112.5024 - mae: 7112.5024
Epoch 40/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 7546.7344 - mae: 7546.7344
Epoch 41/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 7501.2114 - mae: 7501.2114
Epoch 42/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7462.9624 - mae: 7462.9624
Epoch 43/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7532.3662 - mae: 7532.3662
Epoch 44/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7321.5156 - mae: 7321.5156
Epoch 45/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7068.9736 - mae: 7068.9736
Epoch 46/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7061.3345 - mae: 7061.3345
Epoch 47/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7253.3667 - mae: 7253.3667
Epoch 48/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 7337.4653 - mae: 7337.4653
Epoch 49/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 6968.9214 - mae: 6968.9214
Epoch 50/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7422.4053 - mae: 7422.4053
Epoch 51/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7432.7944 - mae: 7432.7944
Epoch 52/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7575.1187 - mae: 7575.1187
Epoch 53/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7018.2236 - mae: 7018.2236
Epoch 54/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7467.1626 - mae: 7467.1626
Epoch 55/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 7399.4893 - mae: 7399.4893
Epoch 56/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7199.3599 - mae: 7199.3599
Epoch 57/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7288.6489 - mae: 7288.6489
Epoch 58/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 7380.0898 - mae: 7380.0898
Epoch 59/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7279.9058 - mae: 7279.9058
Epoch 60/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 7366.1372 - mae: 7366.1372
Epoch 61/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7338.2847 - mae: 7338.2847
Epoch 62/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7373.2349 - mae: 7373.2349
Epoch 63/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7609.7642 - mae: 7609.7642
Epoch 64/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7374.1426 - mae: 7374.1426
Epoch 65/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7402.9180 - mae: 7402.9180
Epoch 66/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7478.8965 - mae: 7478.8965
Epoch 67/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7327.0405 - mae: 7327.0405
Epoch 68/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 7271.4077 - mae: 7271.4077
Epoch 69/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 7226.0117 - mae: 7226.0117
Epoch 70/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7298.4526 - mae: 7298.4526
Epoch 71/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7336.0103 - mae: 7336.0103
Epoch 72/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7310.6816 - mae: 7310.6816
Epoch 73/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7647.6201 - mae: 7647.6201
Epoch 74/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7291.9292 - mae: 7291.9292
Epoch 75/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7524.2544 - mae: 7524.2544
Epoch 76/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 7297.3555 - mae: 7297.3555
Epoch 77/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7254.0332 - mae: 7254.0332
Epoch 78/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7287.4146 - mae: 7287.4146
Epoch 79/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 6836.4497 - mae: 6836.4497
Epoch 80/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7466.2095 - mae: 7466.2095
Epoch 81/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 6894.0762 - mae: 6894.0762
Epoch 82/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7260.7690 - mae: 7260.7690
Epoch 83/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7243.5044 - mae: 7243.5044
Epoch 84/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7043.1372 - mae: 7043.1372
Epoch 85/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7194.2734 - mae: 7194.2734
Epoch 86/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7567.9629 - mae: 7567.9629
Epoch 87/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7201.6909 - mae: 7201.6909
Epoch 88/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7185.3110 - mae: 7185.3110
Epoch 89/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7302.8379 - mae: 7302.8379
Epoch 90/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 7375.4399 - mae: 7375.4399
Epoch 91/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 7441.8496 - mae: 7441.8496
Epoch 92/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 7208.1538 - mae: 7208.1538
Epoch 93/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 7196.9624 - mae: 7196.9624
Epoch 94/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 7154.9326 - mae: 7154.9326
Epoch 95/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 7202.2622 - mae: 7202.2622
Epoch 96/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 7044.0371 - mae: 7044.0371
Epoch 97/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 6833.5293 - mae: 6833.5293
Epoch 98/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7197.3257 - mae: 7197.3257
Epoch 99/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 7107.0718 - mae: 7107.0718
Epoch 100/100
34/34 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 7161.1782 - mae: 7161.1782